version: "3.7"
services:

  web:
    build: .
    container_name: juegos-serios-app
    image: juegos-serios-app
    expose:
      - 80
    depends_on: 
      - mysql
    environment: 
      VIRTUAL_HOST: juegos-serios.localhost
      MYSQL_HOST: juegos-serios-db
      MYSQL_USER: admin
      MYSQL_PASSWORD: 87760jhua
      MYSQL_DATABASE: juegos_serios_db
    networks: 
      - frontend
      - backend

  mysql:
    image: mysql:5.7
    networks:
      - backend
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: admin
      MYSQL_PASSWORD: 87760jhua
      MYSQL_DATABASE: juegos_serios_db
    container_name: juegos-serios-db
    volumes:
      - ./database/webapp_init.sql:/docker-entrypoint-initdb.d/webapp_init.sql  

networks:
  frontend:
    external:
      name: nginx-proxy
  backend: