version: "3.7"
services:

  web:
    build: .
    container_name: juegos_serios-app
    image: juegos_serios-app
    expose: 
      - 80/tcp
    environment: 
      VIRTUAL_HOST: juegos-serios.localhost  
    depends_on: 
      - db
    links:
      - db:mysql
    networks: 
      - default
    volumes: 
      - ./:/var/www/html/

  db:
    image: mysql:5.7
    networks:
      - default
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: root
      MYSQL_PASSWORD: 1992199500Ja
      MYSQL_DATABASE: juegos_serios_db
    container_name: db
    command: --init-file /tmp/database/juegos_serios.sql
    volumes:
      - ./database/juegos_serios.sql:/tmp/database/juegos_serios.sql
  
networks:
  default:
    external:
      name: nginx-proxy